version: '3.8'

services:
  frontend:
    build:
      context: ./movie-review-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/movie_review_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_review_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql-data:

networks:
  my_network:
    driver: bridge
